services:

  api:
    build: ./backend/
    image: backend
    ports:
      - 8000:8000
    environment: 
      SECRET_KEY: /run/secrets/secret_key
      DB_PASSWORD: /run/secrets/db_password
    secrets: 
      - secret_key
      - db_password
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network


  postgres:
    image: postgres:15-alpine
    container_name: postgres_service
    restart: always
    environment:
      POSTGRES_DB: market
      POSTGRES_USER: market_adm
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U market_adm -d market"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_interval: 10s
      start_period: 20s

  

volumes:
  postgres_data: 

networks:
  app-network:
    driver: bridge


secrets:
  db_password:
    file: ./secrets/db_password.txt

  secret_key:
    file: ./secrets/secret_key.txt