from typing import Protocol

from apps.market.entities.cart_item import CartItem


class CartProtocol(Protocol):
    async def get_cart_items(self, tg_id: int, prod_id: int) -> list[CartItem]: ...
    async def add_product(self, tg_id: int, prod_id: int) -> None: ...
    async def change_amount(self, tg_id: int, prod_id: int, increase: bool) -> None: ...
    async def del_from_cart(self, tg_id: int, prod_id: int) -> None: ...
    async def del_cart(self, tg_id: int) -> None: ...
    async def is_user_exists(self, tg_id: int) -> bool: ...
    async def is_product_exists(self, prod_id: int) -> bool: ...
    async def is_cart_item_exists(self, tg_id: int, prod_id: int) -> bool: ...
    async def is_cart_exists(self, tg_id: int) -> bool: ...
