from decimal import Decimal
from typing import Protocol


class CartProtocol(Protocol):
    async def get_cart_items(
        self, tg_id: int, prod_id: int
    ) -> list[dict[str, str | int | Decimal]]: ...
    async def add_product(self, tg_id: int, prod_id: int) -> None: ...
    async def change_amount(self, tg_id: int, prod_id: int, increase: bool) -> None: ...
    async def del_from_cart(self, tg_id: int, prod_id: int) -> None: ...
    async def del_cart(self, tg_id: int): ...
