# Generated by Django 6.0.3 on 2026-03-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_tg_id', models.BigIntegerField(default=0, verbose_name='ID чата администратора')),
            ],
        ),
    ]
