# Generated by Django 6.0.3 on 2026-03-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_profile_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Не отображается у пользователя', max_length=255, verbose_name='Тема (для админки)')),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='newsletters/')),
                ('send_at', models.DateTimeField(verbose_name='Дата и время рассылки')),
                ('status', models.CharField(choices=[('ready', 'Готова к отправке'), ('sent', 'Отправлена'), ('draft', 'Черновик')], default='ready', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, editable=False, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
    ]
