from typing import Protocol

from apps.market.entities.order import Order


class OrderProtocol(Protocol):
    async def create_order(
        self, tg_id: int, address: str, client_full_name: str
    ) -> int: ...
    async def create_order_items(self, tg_id: int, order_id: int) -> None: ...
    async def change_status(self, order_id: int, status: str) -> None: ...
    async def get_all_active_orders(self) -> list[Order]: ...
    async def del_cart(self, tg_id: int) -> None: ...
    async def has_cart(self, tg_id: int) -> bool: ...
    async def is_user_exists(self, tg_id: int) -> bool: ...
    async def is_order_exists(self, order_id: int) -> bool: ...
