from typing import Protocol


class OrderProtocol(Protocol):
    async def create_order(
        self, tg_id: int, address: str, client_full_name: str
    ) -> int: ...
    async def create_order_items(self, tg_id: int, order_id: int) -> None: ...
    async def change_status(self, id: int, status: str) -> None: ...
    async def get_all_active_orders(self) -> dict: ...
