
FROM node:20-alpine AS builder

WORKDIR /app

ARG VITE_USER_ID

ENV VITE_USER_ID=$VITE_USER_ID

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM nginx:stable-alpine

COPY default.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 5173

CMD ["nginx", "-g", "daemon off;"]